---
title       : Subscriber Prediction App
subtitle    : Developing Data Products
author      : rgavuliak
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## The Industry  
  
  
- Publisher's face print circulation and print ad revenues decline as everyone reads on the web  
- Ad revenues for news sites are on a decline too as all the profits go to Google & Facebook  
- Paid content though disliked by the end users and still in its infancy is one of the   solutions

```{r nvd3_inline, results = 'asis', comment = NA, echo = FALSE}
require(rCharts)
require(knitr)
require(rjson)
print_data<-read.csv("newspaper_revenues.csv",sep=";",header=TRUE,check.names=FALSE)
d1<-dPlot(x="Year",y="Print Advertising Revenues",data=print_data,type='line',ylab="Print Revenues")

d1$show('inline', include_assets = TRUE, cdn = TRUE)
cat("<style>.rChart {height: 400px;}</style>")
```
---

## The Trade-offs

- Entering paid content is a challenge for every news organisation
- The ad revenues are still substantial and losing it now may be too soon
- The revenues from a paywall are hard to estimate without any prior data
- New York Times succeeded, but most sites are not NYT

---

## The Solution

- While there are ways to quantify the potential gains and losses either internally or through an external company, not all publishers are willing to make that investment
- That's why we offer the first sanity check in form of this calculator
- If the numbers that come out are of interest then let's talk...
- If they aren't, well you just avoided wasting time, money and other resources you'd
otherwise need to find out the hard way

---

## Notes

- The Calculator is based on a regression model using data from many sites that already
have a paywall
- These are not the only factors that come into play, but it's a start...
- It's actually one of my projects at work!
